name: ultraheatmap
channels:
  - conda-forge
  - bioconda
dependencies:
  - bcftools=1.6
  - bedtools=2.27.1
  - deeptools=3.0.1
  - gffutils=0.9
  - pybedtools=0.7.10
  - pybigwig=0.3.10
  - pyfaidx=0.5.3
  - pysam=0.14.0
  - samtools=1.7
  - python=3.5
  - pyyaml=3.12
