name: ultraheatmap
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >= 3.6
  - bedtools=2.27.1
  - deeptools >= 3.3.1
  - gffutils=0.9
  - pybedtools=0.7.10
  - pybigwig=0.3.10
  - pyyaml >= 5.1
